# DB configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skyx_airlines_flight_mgmt_db
    username:
    password:
    
# Hibernate Configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
# Spring Application Name Configuration 
  application:
    name: skyx-flights-management-service
    
        
#Service end points base path configuration
server:
  servlet:
    context-path: /skyx-airlines/flightservice/
  port: 9002

#Eureka Client instance 
eureka:
  instance:
    hostname: localhost